# Generated by Django 3.1.3 on 2021-03-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expensas',
        ),
    ]
