# Generated by Django 3.1.3 on 2021-03-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensas', '0002_remove_expensas_pago_dpto'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensas',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion'),
        ),
    ]
