# Generated by Django 3.1.3 on 2021-03-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expensas', '0003_expensas_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensas',
            old_name='depto_ph',
            new_name='porcentaja_departamento',
        ),
        migrations.RemoveField(
            model_name='expensas',
            name='porcentaje_correspondiente_dpto',
        ),
    ]
