# Generated by Django 3.1.3 on 2021-03-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_delete_expensas'),
        ('Expensas', '0004_auto_20210310_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensas',
            name='ph_dpto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PH', to='Administracion.departamento'),
        ),
    ]
