# Generated by Django 3.1.3 on 2021-03-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_delete_expensas'),
        ('Expensas', '0005_expensas_ph_dpto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensas',
            name='ph_dpto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='PH', to='Administracion.departamento'),
        ),
    ]
